site_name: RB0011 Soldering Challenge
site_url: https://smd-challenge.robotikabrno.cz
site_author: RoboticsBrno
site_description: >-
  Solving the SMD soldering challenge is a great way to learn how to solder SMD components.
  The challenge is to solder all the components on the PCB in the shortest time possible.
  This challenge contains THT components and SMD components in range from 1206 to 0201.


# Repository
repo_name: RoboticsBrno/RB0011-SolderingChallenge
repo_url: https://github.com/RoboticsBrno/RB0011-SolderingChallenge

# Copyright
copyright: Copyright © 2023 RoboticsBrno

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    # - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: light green
      accent: light green

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobotikaBrno
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robotarna
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@robotikabrno-robotarnaasps2392
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_robotarna_
#    analytics:
#        provider: google
#        property: G-XXXXXXXXXX

use_directory_urls: True

plugins:
  - search
  - glightbox
  - open-in-new-tab
  - mkdocs-video
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English (en)
          build: true
        - locale: cs
          default: false
          name: Czech (cs)
          site_name: RB0011 Pájecí výzva
      reconfigure_material: true
      reconfigure_search: true
  - git-revision-date-localized


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list
  - admonition
  - pymdownx.details
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # - pymdownx.snippets:
  #     url_download: True

nav:
  - Home: 'README.md'
  - soldering.md
  - assembly.md
  - team.md